const actionsTypes = {
  SET_SERVICES_REQUEST: "SET_SERVICES_REQUEST",
  SET_SERVICES_SUCCESS: "SET_SERVICES_SUCCES",
  SET_SERVICES_FAIL: "SET_SERVICES_FAIL",
  LOGIN_SUCCESSFUL:"LOGIN_SUCCESSFUL",
  LOGIN_FAIL:"LOGIN_FAIL"
};

export default actionsTypes;
