export const inputFieldValues =  [
    {
        value:'name',
        name:'name',
        label:'Lugar',
        type:'text',
        error:'name',
        helperText:'name'
    },
    {
        value:'address_1',
        name:'address_1',
        label:'Dirección',
        type:'text',
        error:'address_1',
        helperText:'address_1'
    },
    {
        value:'address_details',
        name:'address_details',
        label:'Piso/Dpto',
        type:'text',
        error:'address_details',
        helperText:'address_details'
    },
    {
        value:'zip_code',
        name:'zip_code',
        label:'Código Postal',
        type:'number',
        error:'zip_code',
        helperText:'zip_code'
    },
    {
        value:'country',
        name:'country',
        label:'País',
        type:'text',
        error:'country',
        helperText:'country'
    },
    {
        value:'state',
        name:'state',
        label:'Provincia',
        type:'text',
        error:'state',
        helperText:'state'
    },
    {
        value:'city',
        name:'city',
        label:'Ciudad',
        type:'text',
        error:'city',
        helperText:'city'
    },
];